# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-20 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('let_me_app', '0020_auto_20170902_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='followable_ptr',
            field=models.OneToOneField(db_column='followable_ptr_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='court_to_follow', serialize=False, to='let_me_app.Followable'),
        ),
        migrations.AlterField(
            model_name='event',
            name='followable_ptr',
            field=models.OneToOneField(db_column='followable_ptr_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='event_to_follow', serialize=False, to='let_me_app.Followable'),
        ),
        migrations.AlterField(
            model_name='site',
            name='followable_ptr',
            field=models.OneToOneField(db_column='followable_ptr_id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='site_to_follow', serialize=False, to='let_me_app.Followable'),
        ),
    ]
