# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-26 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('let_me_app', '0021_auto_20170920_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image'),
        ),
    ]
